apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: kaiburr-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
  